name: chimera
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  # PyTorch stack con versiones específicas y compatibles
  - pytorch::pytorch=2.1.2
  - pytorch::torchvision=0.16.2
  - pytorch::torchaudio=2.1.2
  - pytorch::pytorch-cuda=11.8
  # Fijar NumPy a versión compatible
  - numpy<2
  - graphviz
  - pip
  - pip:
    - transformers
    - timm
    - datasets
    - mlflow
    - conda-lock
    - pynvml
    - ipykernel
    - jupyter
    - ruff
    - black
    - isort
    - pytest
    - uv
    - torchviz
    - torchview
    - torchinfo

